const GET_ALL_BRANDS_DATA = "GET_ALL_BRANDS_DATA";
const GET_ALL_BRANDS_DATA_SUCCESS = "GET_ALL_BRANDS_DATA_SUCCESS";
const GET_ALL_BRANDS_DATA_ERROR = "GET_ALL_BRANDS_DATA_ERROR";
const GET_ALL_MODELS_DATA = "GET_ALL_MODELS_DATA";
const GET_ALL_MODELS_DATA_SUCCESS = "GET_ALL_MODELS_DATA_SUCCESS";
const GET_ALL_MODELS_DATA_ERROR = "GET_ALL_MODELS_DATA_ERROR";
const GET_BRAND_MODELS_DATA = "GET_BRAND_MODELS_DATA";
const GET_BRAND_MODELS_DATA_SUCCESS = "GET_BRAND_MODELS_DATA_SUCCESS";
const GET_BRAND_MODELS_DATA_ERROR = "GET_BRAND_MODELS_DATA_ERROR";
const GET_SERIES_DATA = "GET_SERIES_DATA";
const GET_SERIES_DATA_SUCCESS = "GET_SERIES_DATA_SUCCESS";
const GET_SERIES_DATA_ERROR = "GET_SERIES_DATA_ERROR";
const GET_SERIES_MODELS_DATA = "GET_SERIES_MODELS_DATA";
const GET_SERIES_MODELS_DATA_SUCCESS = "GET_SERIES_MODELS_DATA_SUCCESS";
const GET_SERIES_MODELS_DATA_ERROR = "GET_SERIES_MODELS_DATA_ERROR"; 
const GET_MODELS_VARIANT_DATA = "GET_MODELS_VARIANT_DATA"; 
const GET_MODELS_VARIANT_DATA_SUCCESS = "GET_MODELS_VARIANT_DATA_SUCCESS"; 
const GET_MODELS_VARIANT_DATA_ERROR = "GET_MODELS_VARIANT_DATA_ERROR"; 
const STORE_VARIANT_DATA = "STORE_VARIANT_DATA"; 
const STORE_VARIANT_DATA_SUCCESS = "STORE_VARIANT_DATA_SUCCESS"; 
const STORE_VARIANT_DATA_ERROR = "STORE_VARIANT_DATA_ERROR";   
const GET_QUESTIONS_DATA = "GET_QUESTIONS_DATA";
const GET_QUESTIONS_DATA_SUCCESS = "GET_QUESTIONS_DATA_SUCCESS";
const GET_QUESTIONS_DATA_ERROR = "GET_QUESTIONS_DATA_ERROR";
const GET_PROBLEMS_DATA = "GET_PROBLEMS_DATA";
const GET_PROBLEMS_DATA_SUCCESS = "GET_PROBLEMS_DATA_SUCCESS";
const GET_PROBLEMS_DATA_ERROR = "GET_PROBLEMS_DATA_ERROR";
const STORE_ORDER_PAYLOAD_DATA = "STORE_ORDER_PAYLOAD_DATA";
const STORE_ORDER_PAYLOAD_DATA_SUCCESS = "STORE_ORDER_PAYLOAD_DATA_SUCCESS";
const STORE_ORDER_PAYLOAD_DATA_ERROR = "STORE_ORDER_PAYLOAD_DATA_ERROR"; 
const GET_VERIFY_TOKEN = "GET_VERIFY_TOKEN"; 
const GET_VERIFY_TOKEN_SUCCESS = "GET_VERIFY_TOKEN_SUCCESS"; 
const GET_VERIFY_TOKEN_ERROR = "GET_VERIFY_TOKEN_ERROR"; 
const RESET_TOKEN_DATA = "RESET_TOKEN_DATA"; 
const RESET_TOKEN_DATA_SUCCESS = "RESET_TOKEN_DATA_SUCCESS"; 
const RESET_TOKEN_DATA_ERROR = "RESET_TOKEN_DATA_ERROR"; 
const STORE_EXTRA_MODEL_DATA = "STORE_EXTRA_MODEL_DATA"; 
const STORE_EXTRA_MODEL_DATA_SUCCESS = "STORE_EXTRA_MODEL_DATA_SUCCESS"; 
const STORE_EXTRA_MODEL_DATA_ERROR = "STORE_EXTRA_MODEL_DATA_ERROR"; 
const PLACE_ORDER = "PLACE_ORDER"; 
const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"; 
const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR"; 
const SHOW_ORDER = "SHOW_ORDER"; 
const SHOW_ORDER_SUCCESS = "SHOW_ORDER_SUCCESS"; 
const SHOW_ORDER_ERROR = "SHOW_ORDER_ERROR"; 
const GET_CHAT_DATA = "GET_CHAT_DATA"; 
const GET_CHAT_DATA_SUCCESS = "GET_CHAT_DATA_SUCCESS"; 
const GET_CHAT_DATA_ERROR = "GET_CHAT_DATA_ERROR"; 
const STORE_USET_ID = "STORE_USET_ID"; 
const STORE_USET_ID_SUCCESS = "STORE_USET_ID_SUCCESS"; 
const STORE_USET_ID_ERROR = "STORE_USET_ID_ERROR"; 

export {
  GET_ALL_BRANDS_DATA,
  GET_ALL_BRANDS_DATA_SUCCESS,
  GET_ALL_BRANDS_DATA_ERROR,
  GET_ALL_MODELS_DATA,
  GET_ALL_MODELS_DATA_SUCCESS,
  GET_ALL_MODELS_DATA_ERROR,
  GET_BRAND_MODELS_DATA,
  GET_BRAND_MODELS_DATA_SUCCESS,
  GET_BRAND_MODELS_DATA_ERROR,
  GET_SERIES_DATA,
  GET_SERIES_DATA_SUCCESS,
  GET_SERIES_DATA_ERROR,
  GET_SERIES_MODELS_DATA,
  GET_SERIES_MODELS_DATA_SUCCESS,
  GET_SERIES_MODELS_DATA_ERROR,  
  GET_MODELS_VARIANT_DATA,
  GET_MODELS_VARIANT_DATA_SUCCESS,
  GET_MODELS_VARIANT_DATA_ERROR,
  STORE_VARIANT_DATA,
  STORE_VARIANT_DATA_SUCCESS,
  STORE_VARIANT_DATA_ERROR,  
  GET_QUESTIONS_DATA,
  GET_QUESTIONS_DATA_SUCCESS,
  GET_QUESTIONS_DATA_ERROR,  
  GET_PROBLEMS_DATA,
  GET_PROBLEMS_DATA_SUCCESS,
  GET_PROBLEMS_DATA_ERROR,
  STORE_ORDER_PAYLOAD_DATA,
  STORE_ORDER_PAYLOAD_DATA_SUCCESS,
  STORE_ORDER_PAYLOAD_DATA_ERROR,  
  GET_VERIFY_TOKEN,
  GET_VERIFY_TOKEN_SUCCESS,
  GET_VERIFY_TOKEN_ERROR,
  RESET_TOKEN_DATA,
  RESET_TOKEN_DATA_SUCCESS,
  RESET_TOKEN_DATA_ERROR,  
  STORE_EXTRA_MODEL_DATA,
  STORE_EXTRA_MODEL_DATA_SUCCESS,
  STORE_EXTRA_MODEL_DATA_ERROR,  
  PLACE_ORDER,
  PLACE_ORDER_SUCCESS,
  PLACE_ORDER_ERROR,
  SHOW_ORDER,
  SHOW_ORDER_SUCCESS,
  SHOW_ORDER_ERROR,
  GET_CHAT_DATA,
  GET_CHAT_DATA_SUCCESS,
  GET_CHAT_DATA_ERROR,
  STORE_USET_ID,
  STORE_USET_ID_SUCCESS,
  STORE_USET_ID_ERROR, 
};
